### ISSUE TITLE
"You tried to stop a wad that never played" is unecessary

### ISSUE THREAD

**Issue by Duarte-Dias** [rserota/wad#101]
I stop all my Wads so that only the desired one plays, and this log info is spamming my console. 

I don't find this info of any value and think it should be removed.

**Comment by rserota** [comment]
I just updated the logging system in the latest version of Wad.js. Now, you'll need to manually enable logging by increasing the verbosity of Wad.js: `Wad.logs.verbosity = 1`.

By default, the latest version of Wad.js will print nothing to your console. 

Thanks for using Wad.js and raising this issue.
