### ISSUE TITLE
Have a way to controll all sounds at once

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#103]
Hello,
I'm making a game where a user can focus on a sound and it will get louder. I want all other sounds to stop while this one sound is playing. If there was a master polywad that had all sounds, then I could just call stop on the master polywad, play the new sound and when that finishes, call play on the master wad.
Now I need to loop through a list of all existing sounds and call stop and play  when I want to stop and play them.

**Comment by rserota** [comment]
Well, you totally could just make a PolyWad and add all your other wads to it as they're created. Looping through an array is also a fine solution. 
I guess I could make a 'master PolyWad' that all other wads are added to, but I'm not sure if everyone would want/expect that extra layer of routing set up by default.

**Comment by frastlin** [comment]
precedent for this would include:
[pygame.mixer](https://www.pygame.org/docs/ref/mixer.html)
[howler.js](https://github.com/goldfire/howler.js#global-methods)

Although the single class of Wad doesn't make it very easy to do global functionality.

**Comment by rserota** [comment]
hmm... I might have been overthinking this.
I could add a global method like `Wad.stopAll()` that just calls `stop()` on every wad you've created, and `Wad.setVolume()` that calls `setVolume()` on every wad you've created. Does that sound like what you need?

**Comment by frastlin** [comment]
yes, I want the stop function

**Comment by rserota** [comment]
The latest version of Wad.js includes two new methods, `Wad.stopAll()` and `Wad.setVolume()`.  Thanks for raising this issue, and good luck with your game!
