### ISSUE TITLE
decodedBuffer doesn't contain the audio effects

### ISSUE THREAD

**Issue by Catsvilles** [rserota/wad#106]
So, I'm trying to apply audio effects to a file and get the output as an AudioBuffer and render it as .wav or use with other libraries. But unfortunately even after applying effects to a file and rendering the buffer all I can hear is the original file with no effects. Is it actually possible with Audio Api overall? I know about streaming possibility and capturing the audio with MediaRecorder. But I need it as a background process, possibly with OfflineAudioContext. So, what are my options here? Does AudioNode is the thing that contains all effects and current file? Is there a way to convert it to buffer/.wav? Thanks a lot! :)

**Comment by rserota** [comment]
The decodedBuffer does not include the effects. Effects are applied fresh each time you `play()` a wad. 
I'm pretty sure that what you want to do is possible, but I'm not sure what the easiest way to do it would be. Wad.js used to include [recorder.js](https://github.com/mattdiamond/Recorderjs) to provide this functionality, but recorder.js is no longer being maintained, so I removed the recording features from Wad.js. 
If you check out recorder.js, or one of it's more well-maintained forks, you might be able to hack something together.

**Comment by Catsvilles** [comment]
@rserota Hm, I already use recorder.js and its worker for converting AudioBuffer to .wav, just cannot imagine how could I achieve getting the audio buffer with effects before play(), maybe with OfflineAudioContext? Anyway, I will try again a few 1000 times, maybe eventually I will find a way. :) Thank you very much!
