### ISSUE TITLE
Cross browser issues?

### ISSUE THREAD

**Issue by coleww** [rserota/wad#11]
"Cross-Browser Compatibility
I tried to future-proof Wad.js by using standards-compliant methods, but the cross-browser compatibility is still not great. It works best in Chrome, decently in Safari for iOS, and it works very poorly in Firefox. I have not tested it in any other browsers. I would greatly appreciate contributions to help Wad.js run optimally in any browser that supports Web Audio, especially mobile browsers."

What sorts of issues exists for cross-browser and mobile stuff? I'm interested in working on this.

**Comment by rserota** [comment]
The Web Audio Api seems to still be in flux, and Chrome appears to be the only browser today that natively supports the Web MIDI API, which is really important for me. I'm going to table this issue until these APIs seem more stable.
