### ISSUE TITLE
Adding attenuation to a Wad for 3D Panning?

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#110]
Hello,
I have some objects I want a 10 point attenuation on and some I want a 50 point attenuation on.
How do I set attenuation on a Wad?
Thanks,

**Comment by rserota** [comment]
If I'm understanding you correctly, it sounds like you need to set the [refDistance](https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/refDistance)? Wad.js doesn't support this currently, but I could probably add that feature without too much trouble.

**Comment by frastlin** [comment]
I think I want:
https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/rolloffFactor
I'm not exactly sure what the difference is between the two though.
I want a sound to be completely quiet 10 squares away, but the other sounds to be quiet how they are currently.

**Comment by rserota** [comment]
In version 4.6.0 you can now pass any parameters for 3d panning, including rolloffFactor and refDistance, into the wad constructor, or into the `play()` method. This is mentioned briefly in the docs

**Comment by frastlin** [comment]
It would be nice if you said explicitly the attributes and their default values for rolloffFactor, refDistance, and other attributes, because I don't have the panning node documentation open when I'm using Wad, and I like to know the defaults Wad has set.
