### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by fluse** [rserota/wad#113]
if i use some server side rendered single page frameworks like react and include it with import, i got following error

window is not defined
6|K117  |     at Object.<anonymous> ({pathToProject}/node_modules/web-audio-daw/build/webpack:/Wad/webpack/universalModuleDefinition:10:2)

You should add a check for window is available for server rendering reasons

**Comment by rserota** [comment]
I'm not exactly sure what you expect me to do here? Wad.js runs in the browser, and cares very much about the window. When Wad.js loads initially, it creates an audio context, sets event handlers, requests device access, and other tasks that don't make sense on a server. 
Can't you just defer loading Wad.js until it's running on the client?
