### ISSUE TITLE
Fix Headings in Readme to be in Markdown so the table of contents will work

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#123]
In Markdown, HTML headings don't work when having links like the table of contents. To make headings work, each heading needs an id. Another way is to just use markdown headings like:

`### this is heading 3`

and you link to it by doing:

`[Link to the heading 3](#this-is-heading-3)`

https://gist.github.com/asabaylus/3071099

**Comment by rserota** [comment]
The table of contents seems to be functioning as far as I can tell, but the markup should be cleaned up anyway. 
I was actually planning to rewrite the whole readme in the nearish future.

**Comment by frastlin** [comment]
That would be nice, I would like each function documented, similar to how I did the listener API. The function name, or class name, all the arguments, and a description of each argument.
I also saw some functions in the code that are not in the readme.
When I click on a link, nothing happens.

**Comment by rserota** [comment]
The entire readme has been rewritten, with more comprehensive documentation and proper markdown links.
