### ISSUE TITLE
How to use audio meter without retrieving the tuner's output?

### ISSUE THREAD

**Issue by RizkyArifNur** [rserota/wad#127]
I want to implement pitch detection along with the audiometer, but I don't want to retrieve the tuner's (PolyWad)  output, the example of pitch detection on the Readme shows that we can set the tuner volume to 0 using the **setVolume(0)** method, but when I set the tuner's volume to 0, the **audioMeter.volume** also be zero, is it possible to do the audiometer without retrieving the tuner's output?

**Comment by rserota** [comment]
I think that in order to accomplish what you're trying to do, you would need to use two PolyWads. The inner one should contain the audioMeter and have volume greater than 0, and the outer one should contain the tuner and have its volume set to 0.  
I hope that helps.
