### ISSUE TITLE
I maked some music use this library.

### ISSUE THREAD

**Issue by Lenshang** [rserota/wad#128]
## 1.潮鸣り (from anime Clannad)
Example: https://lenshang.github.io/trigon.js/index.htm?id=1
code: https://github.com/Lenshang/Trigon.js/blob/master/src/songs/clannad.js

## 2.Resserections (from game Celeste)
Example: https://lenshang.github.io/trigon.js/index.htm?id=2
code: https://github.com/Lenshang/Trigon.js/blob/master/src/songs/resserections.js

## 3.LiYue (from game genshin)
Example: https://lenshang.github.io/trigon.js/index.htm?id=3
code: https://github.com/Lenshang/Trigon.js/blob/master/src/songs/liyue.js

## 4.LiYue2 (from game genshin)
Example: https://lenshang.github.io/trigon.js/index.htm?id=4
code: https://github.com/Lenshang/Trigon.js/blob/master/src/songs/liyue2.js

**Comment by rserota** [comment]
I really like these songs, thanks for showing them!  Would you mind if I linked to them in the README, so that other users can get an idea of what is possible with this library?

**Comment by Lenshang** [comment]
> I really like these songs, thanks for showing them! Would you mind if I linked to them in the README, so that other users can get an idea of what is possible with this library?

of course not,and thank you for your star
