### ISSUE TITLE
reverse?

### ISSUE THREAD

**Issue by rexmalebka** [rserota/wad#131]
Hi, is there a way to play in reverse? for example

```javascript
sample.play({rate:-1})
```

**Comment by rserota** [comment]
No, that feature doesn't exist currently. I don't think it would be too hard to build, though.

**Comment by rserota** [comment]
If you pull down version 4.11.0, a new `reverse()` method has been added to the Wad prototype that reverses an audio clip.

**Comment by rexmalebka** [comment]
thank you I have tested.
