### ISSUE TITLE
Pitch detection not working

### ISSUE THREAD

**Issue by animaone** [rserota/wad#132]
The documentation sample provided don't show microphone pitch. Console is showing undefined

**Comment by animaone** [comment]
I don't think it is working. Even if I give permanent permission or if I put it in a click event, console.log still gives me an "undefined".
tested in the last versions of firefox and chrome in linux.

**Comment by ddaniel-gomez** [comment]
It doesnt work for me either. In a simple test in w10/Chrome I get "undefined undefined" whatever I do :(

`<script src="https://unpkg.com/web-audio-daw"></script>
        <script>
            var voice = new Wad({source : 'mic' });
            var tuner = new Wad.Poly();
            tuner.setVolume(0);
            tuner.add(voice);
            voice.play();

            tuner.updatePitch();

            var logPitch = function(){
                console.log(tuner.pitch, tuner.noteName)
                requestAnimationFrame(logPitch)
            };
            logPitch();
            tuner.stopUpdatingPitch();
        </script>`

Regards,
