### ISSUE TITLE
Custom Work

### ISSUE THREAD

**Issue by SESS10NS** [rserota/wad#135]
Dear Sir, we are contacting you from Ethiopia via the UK and are wondering if you are interested in helping us build our online DAW. Kind regards

Rita

Please email me admin@sess10ns.com
or add me on telegram @london2addis We are very interested in becoming a leader in the field of online recording and would love your expertise in assisting us to help musicians create music around the world.

**Comment by SESS10NS** [comment]
Please confirm that you have emailed me as I have received an email claiming to be from you.

**Comment by rserota** [comment]
I have not sent you any email. What address is the email coming from?

**Comment by SESS10NS** [comment]
Its fine it was clarified that it did not come from you but a Lucas Cortez who replied by mistake thinking it was addressed to him for some strange reason... however we are interested in working with you if you are available please can you contact us via admin@sess10ns.com to discuss further please. Kind Regards. Peter
