### ISSUE TITLE
How do I get the playhead position of a Wad object?

### ISSUE THREAD

**Issue by W-KE** [rserota/wad#140]
I'm trying to make a simple music player with Wad, and here is how I used Wad:
```
const audio = new Wad({ source: 'noise' });
console.log(this.audio.duration); // I can get the length of the audio
audio.play();
// is there a way I can get the current playhead position so I can make a progress bar?
```

**Comment by rserota** [comment]
There isn't a single property that provides this information currently, but you can compute the current position like this:

```javascript
const audioClip = new Wad({source: '/audio/song.wav'})
audioClip.play()

let playheadPosition = Wad.audioContext.currentTime - audioClip.lastPlayedTime
```

I hope that helps. Cheers!

**Comment by W-KE** [comment]
Kind of, this only works when you have a fixed playback rate, the position in samples will mismatch with the position calculated this way when playback with a variable rate.

**Comment by rserota** [comment]
Yeah, my solution won't work if you need to adjust the playback rate dynamically, but it's the best solution I can offer you. This is a known issue in the Web Audio API. There's a proposal to add a `position` attribute to the `AudioBufferSourceNode`, but it hasn't been implemented yet.
