### ISSUE TITLE
requestAnimationFrame(logPitch) outputs infinite frame count

### ISSUE THREAD

**Issue by dibyendu1** [rserota/wad#142]
When requestAnimationFrame(logPitch) is called while detecting pitch from the mic, it outputs infinite frame count and doesn't stop even after tuner.stopUpdatingPitch() . How to stop the frame count? 

Additionally, how may pitch recognition start only when the input reaches a certain threshold and end instantly when the microphone receives no input?

**Comment by rserota** [comment]
I swear I was going to look into this, but it seems like the issue has resolved itself?
