### ISSUE TITLE
getUserMedia() build error

### ISSUE THREAD

**Issue by dibyendu1** [rserota/wad#144]
Hi,

I have created a project using Wad in reactJS. 
The project works fine if we use npm start to run the project. But after build it throws an error "getUserMedia is not supported".

**Comment by rserota** [comment]
It's hard for me to help you with so little information. Please use the Bug Report issue template. I can't reproduce this issue.

**Comment by dibyendu1** [comment]
Sure.. I will use the template and create a new thread. For now I am closing this thread. Thank you.
