### ISSUE TITLE
getUserMedia() build error

### ISSUE THREAD

**Issue by dibyendu1** [rserota/wad#145]
I am creating a ReactJS based application where I am using Wad for live pitch detection from the microphone input. When the project is built and run using 'serve -s build', and accessed through **IP_ADDRESS:PORT**, the application throws an error 'getUserMedia is unsupported'. But the application runs well using **localhost:PORT** .

**We observed a strange behaviour. While using localhost:PORT , the browser asks for the permission to access the microphone. But while using IP_ADDRESS:PORT, the browser doesn't ask for permission and the application breaks.**

**To Reproduce**
`  var voice = new Wad({
     source: "mic",
     env: { hold: 1, release: 0 } });
  var tuner = new Wad.Poly();
  tuner.setVolume(0);
  voice.play(0)`

**Device :**
 - Acer Predator Helios 300
 - OS: Ubuntu 22.04
 - Browser Chrome, Mozilla

**Comment by rserota** [comment]
When the project is accessed through the IP address, is it served using HTTPS, or just plain HTTP? `getUserMedia` can only be accessed over HTTPS. This restriction doesn't apply to localhost.

**Comment by dibyendu1** [comment]
Yes I was trying to run the build on http. I will try using https tomorrow and update this issue thread with the results. Thank you for the help.

**Comment by dibyendu1** [comment]
Hi. Yes the application is working fine on https. Thank you for the clarification!!....

**Comment by rserota** [comment]
I'm glad you were able to resolve your issue. I hope you're enjoying using WadJS.
