### ISSUE TITLE
connect output of wads (post processing)

### ISSUE THREAD

**Issue by Kris-rmw** [rserota/wad#149]
I am building an instructional app which compares students singing/playing with the instructor's pre-recorded take. Wad has been extremely useful.

However now I have realised I need more control of pitch analysis, and would therefore like to connect my existing wads ( I have a bunch of them ) with a separate pitch analysis functionality - _after_ effects processing, so that I can re-use my work so far.

Is there a way to accomplish this, ie with Wad.audioContext / createMediaElementSource, or similar?

**Comment by rserota** [comment]
Sure, you can have multiple tuners, analyzing the pitch at multiple points in the effects pipeline. It all depends on how your group wads/polywads together, and where you put the pitch analyzers.

**Comment by Kris-rmw** [comment]
So how would I access a wad's analyser node? I need to send it, as well as the sample rate, to a custom updatePitch() function like this:

```
updatePitch(analyserNode, Wad.audioContext.sampleRate)
```

**Comment by rserota** [comment]
I'm not sure if I understand your use case? Every polywad has a list of the wads it contains in an array called `nodes`. The last node in this list is an analyzer, which is used for pitch detection.

**Comment by Fluxionsdx** [comment]
Hey, I might be able to help you if you can share some code. I'm actually planning to integrate some custom pitch analysis into a music training app as well. I'm down to create an open source module if you want to jam together. Right now I'm just doing single pitch detection, but working on training some neural nets for multi pitch detection. The default single pitch detection is ok, but I find it often mistakes the harmonics for the fundamental.

**Comment by Kris-rmw** [comment]
Thanks - it makes more sense to me now, I ended up using a workaround but will test this next time (being a rookie programmer I am still struggling to get my head around js classes etc).
