### ISSUE TITLE
Pitch Detection example doesn't work

### ISSUE THREAD

**Issue by hassanshaikley** [rserota/wad#151]
**Describe the bug**

https://github.com/rserota/wad#pitch-detection

Doesn't work. Using it in a CRA app and it was printing undefined undefined.

**Expected behavior**

I would expect the note and pitch to get pritned.

**To Reproduce**
Include the smallest possible code snippet that reproduces this bug.

```javascript
import { useEffect } from "react";

import Wad from "web-audio-daw";

export default () => {
  useEffect(() => {
    const voice = new Wad({ source: "mic" }); // At this point, your browser will ask for permission to access your microphone.
    const tuner = new Wad.Poly();
    tuner.setVolume(0); // If you're not using headphones, you can eliminate microphone feedback by muting the output from the tuner.
    tuner.add(voice);

    voice.play(); // You must give your browser permission to access your microphone before calling play().

    tuner.updatePitch(); // The tuner is now calculating the pitch and note name of its input 60 times per second. These values are stored in <code>tuner.pitch</code> and <code>tuner.noteName</code>.

    const logPitch = function () {
      console.log(voice);
      console.log(tuner.pitch, tuner.noteName);
      requestAnimationFrame(logPitch);
    };
    logPitch();
  });

  return <div>Microphone</div>;
};

```

**Screenshots**

**Device (please complete the following information):**
 - Model: [e.g. iPhone6]

**Additional context**

**Comment by rserota** [comment]
I'm unable to reproduce this issue. Can you tell me what browser/OS you're using? Does pitch detection work for you _without_ using react? Does your microphone work for other web audio applications?
