### ISSUE TITLE
Lacking Fb/E#/Cb/B# for Pitch array

### ISSUE THREAD

**Issue by JMTK** [rserota/wad#45]
I can edit it in if you want, but I noticed these are completely missing. Was this intentional?

**Comment by rserota** [comment]
I left them out because I was lazy, and assumed no one would actually want to name their notes that way. If it makes a difference to you, you're welcome to add them in with a pull request.

Thanks for contributing!

**Comment by rserota** [comment]
This issue has been resolved by a pull request.
