### ISSUE TITLE
Can't set destination

### ISSUE THREAD

**Issue by elad661** [rserota/wad#51]
I'm trying to set `destination` when initializing my Wad object, but I'm getting an error: `SyntaxError: An invalid or illegal string was specified`. A quick google search tells me this happens if you try to link nodes from different audio contexts together.

The problem is, since I can't access Wad's own context (I can see where it's defined in wad.js, but I can't access it from a different js file for some reason), I can't create my node in from the same context.

If there was a way to access wad's context from other JS files, or to tell Wad to use my own context, then I could do what I want to do.

**Comment by rserota** [comment]
I pushed an update that addresses this issue. If you pull down the latest version of the code, the audio context that Wad.js creates is assigned to Wad.audioContext, so that you can access it from other scripts. I hope that helps.

**Comment by elad661** [comment]
Awesome, thanks!
