### ISSUE TITLE
Audio stopping itself

### ISSUE THREAD

**Issue by dooxe** [rserota/wad#52]
I have just installed Wad on my website, and made a simple code for playing an audio file: 
var music = new Wad({source : 'app/media/audio/ForgottenPlanet.mp3'});
music.play();

The audio file begins playing, but after some seconds it stops (tested on Firefox and Chrome).

**Comment by rserota** [comment]
Check out this issue from a little while ago: https://github.com/rserota/wad/issues/28

I hope that helps.

**Comment by dooxe** [comment]
Ok nice, it works perfectly.
Sorry for that, I was not able to find the other issues to see if the problem had already been reported.
Thanks a lot !

**Comment by rserota** [comment]
No problem. I'm happy to help.
