### ISSUE TITLE
Move Documentation/Usage into the wiki

### ISSUE THREAD

**Issue by torch2424** [rserota/wad#63]
Hello,

I was reading through the readme, and I was wondering if you would consider moving the usage into the wiki. It is a bit difficult to find what you are looking for with the single page design of the documentation. And the readme could be used a simple desciption of wad, and contain a link to the wiki for documentation

I would be more than happy to help with this in the next couple of weeks if you think it is a good idea.

Thanks!

**Comment by rserota** [comment]
This sounds like a great idea! I really want the documentation for Wad.js to be terrific, but it's definitely been harder to keep it organized in a single page as the library has grown over the years. If you can think of a better way to organize the documentation in the wiki, I'd love to see it.

**Comment by torch2424** [comment]
Awesome! I will see if I can try and get on that soon. I think I might have a good idea, since I was using the library frantically during a hackathon, trying to understand everything as best as I could. I think I have a good idea on it!

I just wanted to confirm with you before I started making any wiki changes haha! I will probably start by plopping the readme into the wiki home, and then going from there
