### ISSUE TITLE
Sound only Plays 3 seconds

### ISSUE THREAD

**Issue by JimScott3305** [rserota/wad#64]
Hello!

I've been experimenting with Wad and no matter what set-up I've given it, the sound (.mp4 file) only plays for 3 or so seconds. The sound is part of a song I edited down to 17 seconds for this trial. I have put it on different web locations, browsers (Chrome 50.x ~ Safari 7.x), tried different songs, etc. - and it plays just a short bit (click the Button, that's all there is to the page):
http://wddtrialdemos.businesscatalyst.com/wadTrial.html

Mac 10.9.5
Any clues or directions to point me?
Thank You,
Jim

**Comment by rserota** [comment]
Thanks for your interest in Wad.js!

This looks like it may be an old issue. All wads have a default 'hold' parameter of about 3 seconds. You might need to manually set it to a larger value. Check out this issue: https://github.com/rserota/wad/issues/28

**Comment by JimScott3305** [comment]
> On Jun 2, 2016, at 8:16 AM, Raphael Serota <notifications@github.com> wrote:
> 
> Thanks for your interest in Wad.js!
> 
> This looks like it may be an old issue. All wads have a default 'hold' parameter of about 3 seconds. You might need to manually set it to a larger value. Check out this issue: #28
> 

Hi Raphael!

Thank You for your quick response - it did the trick (and I now know to also look in the “Closed Issues” section).

Your tagline of “It’s like jQuery for your ears." is perfect, a great simile. So far I have found it easy to use and look forward to exploring Wad further.

I’m working with a program called “Hype Pro" which is an excellent HTML5 animation program for the Mac... but Hype is a little short on Web Audio features. WAD looks it could fill in this blank spot in the feature set, as most of the content creators that use Hype are designers not coders.

I will be playing around with Wad this weekend and look forward to being able to make a recommendation to the Hype forum.

Do You have a “$ Donate” mechanism of some sort that I can reference for others?

Thank You,
Jim Scott

**Comment by rserota** [comment]
I'm glad that resolved your issue. Have fun playing with Wad this weekend!

I don't have a donate mechanism, but thanks for thinking of it. If you'd like to support this project, or encourage others to support this project, I really appreciate stars, forks, and pull-requests.  

Best,
Raphael
