### ISSUE TITLE
Can we manage playing sequence of short duration MP3 files ?

### ISSUE THREAD

**Issue by shivrajsa** [rserota/wad#71]
I have a app developed using  [MIDI.js](https://github.com/mudcube/MIDI.js) where I can create sequence of notes (for song) & play with useful parameters. Mainly I can manage duration of each note.

Can we achieve same using this library? I have set of all MP3 files for notes, is it possible to play them in sequence while controlling duration for each note ?
Please guide.

**Comment by rserota** [comment]
when you call `play()`, you can set a `wait` parameter, which causes the note to not be triggered immediately, but after the amount of time specified by `wait`. Similarly, you can pass an `exactTime` paremeter into `play()`, which uses the webAudio clock to trigger the sound at a specific time. Either of those options should do what you need to do.

**Comment by shivrajsa** [comment]
@rserota Can I use 'for' looop to use `bell.play({wait : 0, env : {hold : .5}})` to play array of notes & wait parameter

**Comment by rserota** [comment]
You sure can. You could try something like this:

`
var notes = [{pitch: "C4", wait: 1}, {pitch: "D4", wait: 2}, {pitch: "E4", wait: 3}];
for (var i = 0; i < notes.length; i++){
   bell.play(notes[i])
}
`
