### ISSUE TITLE
Support of Angular 2

### ISSUE THREAD

**Issue by Apfelkuchen91** [rserota/wad#73]
I want to use this in a Angular 2 App. Is this possible?

**Comment by rserota** [comment]
I haven't tried it, but I don't see why not. Wad doesn't care at all about the view, and Angular 2 doesn't care too much about audio, so they shouldn't interfere with each other.

**Comment by Fluxionsdx** [comment]
I have an app that I just converted to Angular 2 and it works fine. Just
require it in the file where you need it.
