### ISSUE TITLE
Wad features

### ISSUE THREAD

**Issue by berserk82** [rserota/wad#74]
Hello everyone.
My name is Ivano Arrighetta and I'm Italian.
I wonder if Wad supports these features:
filters:
lowpass
highpass
bandpass
notch

note playing:
chords
arpeggio

other:
mixer (assigning any audio output to a "virtual group")
loop points

Thanks in advance for any help.

Bye, Ivano.

**Comment by rserota** [comment]
Hi Ivano,
Thanks for your interest in wad.js.

Wad.js supports the filters you mentioned. 

Wad.js does not explicitly have a 'chord' or 'arpeggio' feature, but you can play any notes you want to, and use the `wait` parameter to control exactly when the notes play. This way, you can play any chords or arpeggios you want. 

By wrapping multiple wads in a polywad, you can emulate a mixer track, in which multiple instruments receive the same set of effects. 

If you search through the documentation, you should find examples of how to use filters, set up mixer tracks, etc.

I'm not exactly sure what you mean by 'loop points'. If you elaborate on that, I might be able to help you?

Best,
Raphael

**Comment by berserk82** [comment]
Thanks a lot for your answer.
By "loop points", I mean a start and end loop markers, which makes a part of the song playing on forever or a certain number of times.

Bye, Ivano.

**Comment by rserota** [comment]
There aren't any built-in looping features in Wad.js, but you can probably create something close to what you're looking for using delay nodes, and routing their output into their input. It might take a bit of work to get it the way you want, though.

**Comment by berserk82** [comment]
Will you implement it?

**Comment by berserk82** [comment]
Yes, you're right. Thanks.

**Comment by Fluxionsdx** [comment]
Glad to help.
