### ISSUE TITLE
Accessing the Audio Listener Object through WAD?

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#78]
Hello,
Could support for the AudioListener object please be added so effective use of 3D audio can be achieved through WAD?
https://developer.mozilla.org/en-US/docs/Web/API/AudioListener

This is accessed by audioCtx.listener.
Currently the only way I know to access this is by accessing the audio context directly. I would prefer to go through WAD.
Thanks,

**Comment by rserota** [comment]
You can access the audio listener through `Wad.audioContext.listener`.

**Comment by frastlin** [comment]
can documentation for Wad.audioContext.listener please be added, or can there be a Wad.listener object? The big thing is the documentation though.
Thanks,

**Comment by rserota** [comment]
The documentation currently describes `Wad.audioContext`, near the end. The audio context contains [all of its usual properties](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext), including the audio listener.
