### ISSUE TITLE
Changing the Rate of a Sound

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#83]
Is there any way of changing the speed and or pitch of a recorded sound? Something along the lines of:
sound.rate(1.5)
or
sound.speed(1.5)
or
sound.pitch(1.5)

I know you can change the speed and pitch of oscillators, but I would like to change the pitch of a recorded sound. Howler does this with sound.rate(1.5).

**Comment by rserota** [comment]
Wads do have a `setSpeed` method, but they didn't have speed available as an argument on the constructor, or on play. I just added speed as an argument, so now you should be able to play audio clips at different speeds.

`var audioClip = new Wad({source:'./audio-clip.mp3'})`
`audioClip.play({speed: 0.5})`
`audioClip.play({speed: 2.0})`

**Comment by frastlin** [comment]
Thank you, it works perfectly!
I would personally hesitate at calling it "speed" because it is both speed and pitch, and instead call it rate, but it's not a big deal.
