### ISSUE TITLE
Creating Audio Sprites

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#84]
Hello,
I would like support for audio sprites. Basically loading one long file that contains many sound effects that I can label and set the start and end values of.
This can be defined during the constructor as follows:
sprite: {
'labelName': [0, 500]
}
where the first number represents the offset  and the second number represents the end value.
This is good for loading large amounts of sound effects for games, hacking soundfonts, making lists of sound effects, loading speech clips, and doing anything where there will be a lot of repetitive playing of many sound effects.
howlerJS has an implantation of this for reference.
Thanks,

**Comment by frastlin** [comment]
Here is a link describing the pros and cons of audio sprites and an implementation:
https://www.createjs.com/docs/soundjs/classes/AudioSprite.html

**Comment by rserota** [comment]
Audio sprites should now work in 4.1.1. Thanks for the suggestion.
