### ISSUE TITLE
Making play a Promise

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#86]
Hello,
Would it be possible to make play a Promise? I have some situations where I need to play sounds one after another and at the moment, I can only do this by setTimeout(callback, sound.decodedBuffer.duration)
Being able to use await would save a lot of extra coding on my part and would make the play function very useful for split scenes, footsteps, or any sequential sounds.

**Comment by rserota** [comment]
In the latest version of Wad.js, `play()` now returns a promise.

Thanks for the suggestion.
