### ISSUE TITLE
allow for a -1 hold value on Oscillators so they never stop

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#90]
I don't want an oscillator to stop until I call stop() on it. the docs say:

>         hold    : 3.14, // Time in seconds to maintain the sustain volume level. If this is not set to a lower value, oscillators must be manually stopped by calling their stop() method.

This makes it sound as if I set hold to 4, it will not stop until I call stop(). This is not the case, setting hold to 4 holds for 4 seconds.
I would like a -1 value that allows the sound to play until I call stop on it.

**Comment by rserota** [comment]
Sure, why not.
