### ISSUE TITLE
setting pitch doesn't seem to work

### ISSUE THREAD

**Issue by weepy** [rserota/wad#92]
using the version on npm. 

The detune and rate does seem to work. 

Any pointers ?

**Comment by rserota** [comment]
Are you getting any errors in the console, or does it just have no effect?

I'm in the middle of moving right now, so I might not be able to look into this for a little while.

**Comment by weepy** [comment]
no errors - just no effect.

Seems detune works in chrome but not safari, but
just hacking round it by setting rate which seems to work for both

**Comment by rserota** [comment]
I just tested the `setPitch` functionality in Chrome on mac, and it seems to be working fine, as far as I can tell. Do you want to share your code that wasn't working?
