### ISSUE TITLE
Tuna Phaser not working

### ISSUE THREAD

**Issue by scrapcupcake** [rserota/wad#93]
```
new Wad({
        source: 'sine',
        pitch: 'B4',
        env: {
            attack: 0.1,
            sustain:0.2,
            hold: 0.2,
            decay: 0.4
        },
        tuna: {
            Phaser: {
                rate: 1.2,                     //0.01 to 8 is a decent range, but higher values are possible
                depth: 0.3,                    //0 to 1
                feedback: 0.2,                 //0 to 1+
                stereoPhase: 30,               //0 to 180
                baseModulationFrequency: 700,  //500 to 1500
                bypass: 0
            },
            // WahWah: {
            //     automode: true,                //true/false
            //     baseFrequency: 0.5,            //0 to 1
            //     excursionOctaves: 2,           //1 to 6
            //     sweep: 0.2,                    //0 to 1
            //     resonance: 10,                 //1 to 100
            //     sensitivity: 0.5,              //-1 to 1
            //     bypass: 0
            // }
        }
    })
```

WahWah, Overdrive, Chorus, Delay all seem to work fine, but this generates no sound. Am I doing it wrong?

**Comment by rserota** [comment]
Your code looks reasonable. 
Wad.js handles all tuna effects in the same way, so I can't imagine why some of them would work, but not others. Have you tried using Tuna's phaser _without_ wad.js?

I should have some time to actually investigate this over this weekend.

**Comment by rserota** [comment]
I tried testing out the Phaser using the same parameters you're using above, and everything seems to be working fine, as far as I can tell. 
To be clear, when you say 'this generates no sound', do you mean that you hear literally nothing from your speakers, or that the phaser isn't affecting the sound at all?
Are there any errors in your console? 
What browser/OS are you using?

Either way, thanks for using Wad.js. I hope you're enjoying it.

**Comment by scrapcupcake** [comment]
I'll retest, probably a browser bug in retrospect, will update in 1-2 days,
holidays yo

**Comment by scrapcupcake** [comment]
Retested, appears to be a browser bug, closing <3
