### ISSUE TITLE
Changing tuna Settings During Playback

### ISSUE THREAD

**Issue by richtier** [rserota/wad#95]
I see it's possible to [set wad settings during playback](https://github.com/rserota/wad#changing-settings-during-playback)

Can tuna settings also be set in this way?

**Comment by rserota** [comment]
There isn't a very elegant way to do this at the moment. I can work on adding this at some point in the future.

**Comment by richtier** [comment]
All of them :)

I'm making a demo of [alexa-browser-client](https://github.com/richtier/alexa-browser-client/pull/24) - using wad and tuna to mess with the alexa audio response. I can now make Alexa sound like she's behind a door, an old-timey radio, or a train station announcer. so happy :laughing: 

![mixer](https://user-images.githubusercontent.com/5485798/51542311-d919a980-1e52-11e9-9847-34fbfe1892e2.gif)


tuna supports updating after play has started: https://github.com/Theodeus/tuna/issues/64#issuecomment-456194388

**Comment by rserota** [comment]
That looks like a pretty cool project!

I know that Tuna makes this possible, but it just isn't part of the Wad.js API yet. As a workaround, you can directly modify a Wad's tuna nodes while it's playing.  

```
wadSound.play()
wadSound.nodes[2].rate = 8 // the actual index of the tuna effect node will depend on how many other effects are used in this wad. 
```

**Comment by richtier** [comment]
this works great, thanks.
